// Generated by https://quicktype.io

export interface ReqRestList {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        UsersIO[];
    support:     Support;
}

export interface UsersIO {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}

export interface Support {
    url:  string;
    text: string;
}

/*
nah diatas kita udah dapat interface sbgai typedata validator atau identity 
nah jadi udah match contract antara client dan server 
diatas interface users pada reqResList adalah array dari Users itnerface object literal 
yg artinya sprtin ini [ {},{},{}]
nah kita akan buat useState atau buat variable data state utk tampung data dari server 
cara di Users.tsx kita impor interface diatas  dan declare dgn useSate 
const [dataUser,setDataUser] = useState<Users[]>([]) 
//dimana degaultnya adalah sbuah array kosong 

nah kita buat map pada td yaitu di body kmudian utk td kita masukan di situ maping
bisa langsung atau bisa caranya di buat function dan "direferensikan" 
*/


/*
mapping cara langsung
*/

/*
maing direferensikan 


*/